# permissions for end users to view endpointsliceshadows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: endpointsliceshadow-viewer-role
rules:
- apiGroups:
  - puregw.acnodal.io
  resources:
  - endpointsliceshadows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - puregw.acnodal.io
  resources:
  - endpointsliceshadows/status
  verbs:
  - get
