# permissions for end users to edit endpointsliceshadows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: endpointsliceshadow-editor-role
rules:
- apiGroups:
  - puregw.epic-gateway.org
  resources:
  - endpointsliceshadows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - puregw.epic-gateway.org
  resources:
  - endpointsliceshadows/status
  verbs:
  - get
