# permissions for end users to view gatewayclassconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gatewayclassconfig-viewer-role
rules:
- apiGroups:
  - puregw.acnodal.io
  resources:
  - gatewayclassconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - puregw.acnodal.io
  resources:
  - gatewayclassconfigs/status
  verbs:
  - get
