---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: system
spec:
  template:
    spec:
      hostAliases:
      - ip: 192.168.254.21
        hostnames:
        - gwdev-ctl
      - ip: 192.168.254.200
        hostnames:
        - acndev-ctl
      - ip: 72.52.66.46
        hostnames:
        - epic-ctl
