---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
spec:
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - image: purelb/kuard-amd64:blue
        name: kuard
      topologySpreadConstraints:
      - topologyKey: kubernetes.io/hostname
        maxSkew: 1
        labelSelector:
          matchLabels:
            app: sample
        whenUnsatisfiable: ScheduleAnyway
