## Append samples you want in your CSV to this file as resources ##
resources:
- puregw_v1_gatewayclassconfig.yaml
- gateway_v1alpha2_gateway.yaml
- discovery_v1_endpointslice.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
