---
apiVersion: puregw.epic-gateway.org/v1
kind: GatewayClassConfig
metadata:
  name: epic-sample
spec:
  epic:
    cluster-name: epic-sample
    gateway-hostname: gwdev-ctl
    service-account: user1
    service-key: password1
    user-namespace: root
    gateway-template: gatewayhttp
  trueIngress:
    decapAttachment:
      direction: ingress
      interface: default
      flags: 1
      qid: 0
    encapAttachment:
      direction: egress
      interface: default
      flags: 20
      qid: 1
