---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: agent
  namespace: system
  labels:
    control-plane: agent
spec:
  selector:
    matchLabels:
      control-plane: agent
  template:
    metadata:
      labels:
        control-plane: agent
    spec:
      containers:
      - name: agent
        command:
        - /agent
        env:
        - name: EPIC_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: controller:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_ADMIN
            drop:
            - ALL
          readOnlyRootFilesystem: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
      hostNetwork: true
      serviceAccountName: manager
      terminationGracePeriodSeconds: 5
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
