---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: controller-agent
  namespace: system
  labels:
    control-plane: controller-agent
spec:
  selector:
    matchLabels:
      control-plane: controller-agent
  template:
    metadata:
      annotations:
        prometheus.io/port: '7472'
        prometheus.io/scrape: 'true'
      labels:
        control-plane: controller-agent
    spec:
      containers:
      - name: agent
        command:
        - /agent
        env:
        - name: EPIC_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: EPIC_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        image: controller:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7472
          name: monitoring
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_ADMIN
            drop:
            - ALL
          readOnlyRootFilesystem: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
      hostNetwork: true
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 2
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
