//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Acnodal.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/gateway-api/apis/v1alpha2"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Attachment) DeepCopyInto(out *Attachment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Attachment.
func (in *Attachment) DeepCopy() *Attachment {
	if in == nil {
		return nil
	}
	out := new(Attachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EPIC) DeepCopyInto(out *EPIC) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EPIC.
func (in *EPIC) DeepCopy() *EPIC {
	if in == nil {
		return nil
	}
	out := new(EPIC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointSliceShadow) DeepCopyInto(out *EndpointSliceShadow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointSliceShadow.
func (in *EndpointSliceShadow) DeepCopy() *EndpointSliceShadow {
	if in == nil {
		return nil
	}
	out := new(EndpointSliceShadow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EndpointSliceShadow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointSliceShadowList) DeepCopyInto(out *EndpointSliceShadowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EndpointSliceShadow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointSliceShadowList.
func (in *EndpointSliceShadowList) DeepCopy() *EndpointSliceShadowList {
	if in == nil {
		return nil
	}
	out := new(EndpointSliceShadowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EndpointSliceShadowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointSliceShadowSpec) DeepCopyInto(out *EndpointSliceShadowSpec) {
	*out = *in
	if in.ParentRoutes != nil {
		in, out := &in.ParentRoutes, &out.ParentRoutes
		*out = make([]v1alpha2.ParentRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointSliceShadowSpec.
func (in *EndpointSliceShadowSpec) DeepCopy() *EndpointSliceShadowSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointSliceShadowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointSliceShadowStatus) DeepCopyInto(out *EndpointSliceShadowStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointSliceShadowStatus.
func (in *EndpointSliceShadowStatus) DeepCopy() *EndpointSliceShadowStatus {
	if in == nil {
		return nil
	}
	out := new(EndpointSliceShadowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayClassConfig) DeepCopyInto(out *GatewayClassConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayClassConfig.
func (in *GatewayClassConfig) DeepCopy() *GatewayClassConfig {
	if in == nil {
		return nil
	}
	out := new(GatewayClassConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GatewayClassConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayClassConfigList) DeepCopyInto(out *GatewayClassConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GatewayClassConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayClassConfigList.
func (in *GatewayClassConfigList) DeepCopy() *GatewayClassConfigList {
	if in == nil {
		return nil
	}
	out := new(GatewayClassConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GatewayClassConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayClassConfigSpec) DeepCopyInto(out *GatewayClassConfigSpec) {
	*out = *in
	if in.EPIC != nil {
		in, out := &in.EPIC, &out.EPIC
		*out = new(EPIC)
		**out = **in
	}
	if in.TrueIngress != nil {
		in, out := &in.TrueIngress, &out.TrueIngress
		*out = new(TrueIngress)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayClassConfigSpec.
func (in *GatewayClassConfigSpec) DeepCopy() *GatewayClassConfigSpec {
	if in == nil {
		return nil
	}
	out := new(GatewayClassConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayClassConfigStatus) DeepCopyInto(out *GatewayClassConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayClassConfigStatus.
func (in *GatewayClassConfigStatus) DeepCopy() *GatewayClassConfigStatus {
	if in == nil {
		return nil
	}
	out := new(GatewayClassConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrueIngress) DeepCopyInto(out *TrueIngress) {
	*out = *in
	out.EncapAttachment = in.EncapAttachment
	out.DecapAttachment = in.DecapAttachment
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrueIngress.
func (in *TrueIngress) DeepCopy() *TrueIngress {
	if in == nil {
		return nil
	}
	out := new(TrueIngress)
	in.DeepCopyInto(out)
	return out
}
